CREATE TABLE IF NOT EXISTS `#__mailer_node` (
 `mailerid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
 `namekey` varchar(150) NOT NULL,
 `alias` varchar(150) NOT NULL,
 `type` tinyint(3) unsigned NOT NULL DEFAULT '1',
 `rolid` smallint(5) unsigned NOT NULL DEFAULT '1',
 `uid` int(10) unsigned NOT NULL DEFAULT '0',
 `modifiedby` int(10) unsigned NOT NULL DEFAULT '0',
 `core` tinyint(4) NOT NULL DEFAULT '0',
 `publish` tinyint(4) NOT NULL DEFAULT '0',
 `created` int(10) unsigned NOT NULL DEFAULT '0',
 `modified` int(10) unsigned NOT NULL DEFAULT '0',
 `sendername` varchar(100) NOT NULL,
 `senderemail` varchar(100) NOT NULL,
 `replyname` varchar(100) NOT NULL,
 `replyemail` varchar(100) NOT NULL,
 `bouncebackemail` varchar(100) NOT NULL,
 `embedimages` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `multiplepart` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `encodingformat` varchar(50) NOT NULL,
 `charset` varchar(100) NOT NULL,
 `wordwrapping` int(10) unsigned NOT NULL DEFAULT '0',
 `addnames` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `params` text NOT NULL,
 `premium` tinyint(4) NOT NULL DEFAULT '0',
 `designation` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `ordering` smallint(5) unsigned NOT NULL DEFAULT '9',
 `hostname` varchar(254) NOT NULL,
 PRIMARY KEY (`mailerid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;